<?php

namespace App\Controllers;

use PDO;

class ExportController
{
    private PDO $db;

    public function __construct()
    {
        $this->db = \App\Config\Database::getConnection();
    }

    public function export(): void
    {
        $userId = \App\Middleware\AuthMiddleware::getUserId();
        $input = $this->getJsonInput();

        $format = $input['format'] ?? 'pdf';
        $analysisId = $input['analysis_id'] ?? null;

        if (!$analysisId) {
            Response::error('analysis_id is required', 400);
            return;
        }

        // Get analysis
        $sql = "SELECT * FROM cv_analyses WHERE id = :id AND user_id = :user_id LIMIT 1";
        $stmt = $this->db->prepare($sql);
        $stmt->execute([':id' => $analysisId, ':user_id' => $userId]);
        $analysis = $stmt->fetch();

        if (!$analysis) {
            Response::error('Analysis not found', 404);
            return;
        }

        $analysis['analysis_data'] = json_decode($analysis['analysis_data'], true);

        switch ($format) {
            case 'json':
                $this->exportJSON($analysis);
                break;
            case 'html':
                $this->exportHTML($analysis);
                break;
            case 'docx':
                $this->exportDOCX($analysis);
                break;
            default:
                Response::error('Unsupported export format. Use: json, html, docx', 400);
        }
    }

    private function exportJSON(array $analysis): void
    {
        header('Content-Type: application/json');
        header('Content-Disposition: attachment; filename="cv-analysis-' . $analysis['id'] . '.json"');

        echo json_encode($analysis['analysis_data'], JSON_PRETTY_PRINT);
        exit;
    }

    private function exportHTML(array $analysis): void
    {
        $data = $analysis['analysis_data'];

        header('Content-Type: text/html');
        header('Content-Disposition: attachment; filename="cv-analysis-' . $analysis['id'] . '.html"');

        $html = $this->renderHTML($data);

        echo $html;
        exit;
    }

    private function renderHTML(array $data): string
    {
        $score = $data['scores']['overall'] ?? 0;
        $scoreColor = $score >= 80 ? '#22c55e' : ($score >= 60 ? '#eab308' : '#ef4444');

        ob_start();
        ?>
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>CV Analysis Report</title>
            <style>
                body { font-family: 'Segoe UI', Arial, sans-serif; max-width: 900px; margin: 0 auto; padding: 40px; background: #0f172a; color: #e2e8f0; line-height: 1.6; }
                h1, h2, h3 { color: #22d3ee; }
                .header { text-align: center; margin-bottom: 40px; border-bottom: 2px solid #1e293b; padding-bottom: 20px; }
                .score-circle { width: 150px; height: 150px; border-radius: 50%; background: conic-gradient(<?= $scoreColor ?> <?= $score * 3.6 ?>deg, #1e293b 0); display: flex; align-items: center; justify-content: center; margin: 20px auto; }
                .score-inner { width: 120px; height: 120px; border-radius: 50%; background: #0f172a; display: flex; align-items: center; justify-content: center; font-size: 48px; font-weight: bold; color: <?= $scoreColor ?>; }
                .section { background: #1e293b; padding: 25px; margin: 25px 0; border-radius: 12px; border-left: 4px solid #0ea5e9; }
                .skill-tag { display: inline-block; background: #0ea5e9; color: white; padding: 6px 14px; margin: 5px; border-radius: 20px; font-size: 14px; }
                .metrics { display: grid; grid-template-columns: repeat(4, 1fr); gap: 15px; margin: 20px 0; }
                .metric { text-align: center; padding: 15px; background: #1e293b; border-radius: 8px; }
                .metric-value { font-size: 28px; font-weight: bold; margin: 10px 0; }
                .positive { color: #22c55e; }
                .neutral { color: #eab308; }
                .negative { color: #ef4444; }
                .list-item { margin: 8px 0; padding-left: 20px; position: relative; }
                .list-item:before { content: "→"; position: absolute; left: 0; color: #22d3ee; }
                ul { padding-left: 20px; }
            </style>
        </head>
        <body>
            <div class="header">
                <h1>CV Analysis Report</h1>
                <p>Generated by CV Analyzer</p>
                <p><?= date('F j, Y') ?></p>
            </div>

            <?php if (isset($data['personalInfo']['name'])): ?>
            <div class="section">
                <h2>Candidate</h2>
                <p><strong>Name:</strong> <?= htmlspecialchars($data['personalInfo']['name']) ?></p>
                <?php if (isset($data['personalInfo']['email'])): ?>
                <p><strong>Email:</strong> <?= htmlspecialchars($data['personalInfo']['email']) ?></p>
                <?php endif; ?>
            </div>
            <?php endif; ?>

            <div class="section">
                <h2>Overall Score</h2>
                <div class="score-circle">
                    <div class="score-inner"><?= $score ?>%</div>
                </div>

                <div class="metrics">
                    <div class="metric">
                        <div>ATS</div>
                        <div class="metric-value <?= ($data['scores']['ats'] ?? 0) >= 70 ? 'positive' : (($data['scores']['ats'] ?? 0) >= 50 ? 'neutral' : 'negative') ?>">
                            <?= $data['scores']['ats'] ?? 0 ?>%
                        </div>
                    </div>
                    <div class="metric">
                        <div>Readability</div>
                        <div class="metric-value <?= ($data['scores']['readability'] ?? 0) >= 70 ? 'positive' : (($data['scores']['readability'] ?? 0) >= 50 ? 'neutral' : 'negative') ?>">
                            <?= $data['scores']['readability'] ?? 0 ?>%
                        </div>
                    </div>
                    <div class="metric">
                        <div>Impact</div>
                        <div class="metric-value <?= ($data['scores']['impact'] ?? 0) >= 70 ? 'positive' : (($data['scores']['impact'] ?? 0) >= 50 ? 'neutral' : 'negative') ?>">
                            <?= $data['scores']['impact'] ?? 0 ?>%
                        </div>
                    </div>
                    <div class="metric">
                        <div>Completeness</div>
                        <div class="metric-value <?= ($data['scores']['completeness'] ?? 0) >= 70 ? 'positive' : (($data['scores']['completeness'] ?? 0) >= 50 ? 'neutral' : 'negative') ?>">
                            <?= $data['scores']['completeness'] ?? 0 ?>%
                        </div>
                    </div>
                </div>
            </div>

            <?php if (!empty($data['skills'])): ?>
            <div class="section">
                <h2>Skills Identified (<?= count($data['skills']) ?>)</h2>
                <div>
                    <?php foreach ($data['skills'] as $skill): ?>
                        <span class="skill-tag"><?= htmlspecialchars($skill['name']) ?></span>
                    <?php endforeach; ?>
                </div>
            </div>
            <?php endif; ?>

            <?php if (!empty($data['feedback']['strengths'])): ?>
            <div class="section">
                <h2>Strengths</h2>
                <ul>
                    <?php foreach ($data['feedback']['strengths'] as $strength): ?>
                        <li class="list-item"><?= htmlspecialchars($strength) ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <?php endif; ?>

            <?php if (!empty($data['feedback']['improvements'])): ?>
            <div class="section">
                <h2>Areas for Improvement</h2>
                <ul>
                    <?php foreach ($data['feedback']['improvements'] as $improvement): ?>
                        <li class="list-item"><?= htmlspecialchars($improvement) ?></li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <?php endif; ?>

            <?php if (isset($data['experience'])): ?>
            <div class="section">
                <h2>Experience Level</h2>
                <p><strong>Years of Experience:</strong> <?= $data['experience']['years'] ?? 0 ?></p>
                <p><strong>Level:</strong> <?= ucfirst($data['experience']['level'] ?? 'N/A') ?></p>
            </div>
            <?php endif; ?>

            <div class="section">
                <h2>Keywords</h2>
                <div>
                    <?php foreach ($data['feedback']['keywords'] ?? [] as $keyword): ?>
                        <span class="skill-tag" style="background: #64748b;"><?= htmlspecialchars($keyword) ?></span>
                    <?php endforeach; ?>
                </div>
            </div>

            <footer style="text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #1e293b; color: #64748b;">
                <p>Report generated by CV Analyzer • <a href="https://cardzey.com" style="color: #22d3ee;">cardzey.com</a></p>
            </footer>
        </body>
        </html>
        <?php
        return ob_get_clean();
    }

    private function exportDOCX(array $analysis): void
    {
        header('Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document');
        header('Content-Disposition: attachment; filename="cv-analysis-' . $analysis['id'] . '.docx"');

        // Simple DOCX generation (basic template)
        // For production, use PHPWord library (requires Composer)
        // For now, generate a simple text file with .docx extension
        $data = $analysis['analysis_data'];
        $content = "CV ANALYSIS REPORT\n";
        $content .= "==================\n\n";
        $content .= "Overall Score: " . ($data['scores']['overall'] ?? 0) . "%\n\n";
        $content .= "Skills:\n";
        foreach ($data['skills'] ?? [] as $skill) {
            $content .= "- " . $skill['name'] . " (" . $skill['category'] . ")\n";
        }
        $content .= "\nStrengths:\n";
        foreach ($data['feedback']['strengths'] ?? [] as $s) {
            $content .= "✓ " . $s . "\n";
        }
        $content .= "\nImprovements:\n";
        foreach ($data['feedback']['improvements'] ?? [] as $i) {
            $content .= "→ " . $i . "\n";
        }

        echo $content;
        exit;
    }

    private function getJsonInput(): array
    {
        $input = file_get_contents('php://input');
        $data = json_decode($input, true);

        return is_array($data) ? $data : [];
    }
}
